version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    assignees:
      - "cedricziel"
    reviewers:
      - "cedricziel"
    commit-message:
      prefix: "chore"
      include: "scope"
