name: stability_ai_dart
description: A comprehensive Dart library for the Stability AI REST API.
  Supports text-to-image, upscaling, and SD 3.0/3.5.
version: 1.0.3
homepage: https://github.com/cedricziel/stabilityai-dart
repository: https://github.com/cedricziel/stabilityai-dart
issue_tracker: https://github.com/cedricziel/stabilityai-dart/issues

example: example/stability_ai_dart_example.dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.7.1
  lints: ">=2.1.1 <6.0.0"
  mockito: ^5.4.5
  test: ^1.25.14
