name: stability_ai_dart
description: A Dart library for interacting with the Stability AI REST API
version: 0.1.0
homepage: https://github.com/cedricziel/stabilityai-dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.7.1
  lints: ^2.1.1
  mockito: ^5.4.5
  test: ^1.25.14
